[package]
name = "blockfrost"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "0.3.3"
>>>>>>> c7f0f36 (add missing TransactionOutputs fields)
edition = "2021"
keywords = ["blockfrost", "blockchain", "cardano", "ipfs", "nft"]
categories = ["api-bindings", "asynchronous", "cryptography::cryptocurrencies"]
description = "A Rust SDK for Blockfrost.io API"
license = "Apache-2.0"
repository = "https://github.com/blockfrost/blockfrost-rust"
homepage = "https://blockfrost.io"

[dependencies]
blockfrost-openapi = { version = "0.0.3" }
futures = "0.3.17"
reqwest = { version = "0.11.4", features = ["multipart", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
paste = "1.0"
toml = "0.8.2"
url = "2.4.1"
thiserror = "1.0.50"

[dev-dependencies]
async-trait = "0.1.74"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
